# Generated by Django 6.0.6 on 2026-06-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedirectRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_url", models.TextField()),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (301, "301 - Permanent"),
                            (302, "302 - Temporary"),
                            (307, "307 - Temporary, same HTTP method"),
                            (308, "308 - Permanent, same HTTP method"),
                        ],
                        default=302,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("preserve_query", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
                "db_table": "redirects",
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RedirectPath",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "redirect",
                        "source_path",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_path", models.CharField(max_length=255, unique=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "redirect",
                    models.ForeignKey(
                        db_column="redirect_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_rows",
                        to="redirects.redirectrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "redirect path",
                "verbose_name_plural": "redirect paths",
                "db_table": "redirect_paths",
                "ordering": ["position", "source_path"],
            },
        ),
    ]
