# Generated by Django 6.0.6 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notepad", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
